config/routes.rb
MallorcaRoR::Application.routes.draw do
  root :to => 'home#index'
  get 'home' => 'home#index', :as => 'home'
  get 'login' => 'users#login_index', :as => 'login'
  post 'login' => 'users#login', :as => 'login'
  get 'logout' => 'users#destroy_session', :as => 'logout'
  
  
  resources :meetups

  resources :users
  
  resources :blogs, :only => [:new, :create, :edit]
  get 'blog' => 'blogs#index', :as => 'blog'
  match 'blog.:id' => 'blogs#update', :via => :put
  match 'delete_blog.:id' => 'blogs#destroy', :as => 'delete_blog'
  
  resources :topics
  
  resources :tasks
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :image_path, :image_path_home, :long_desc, :short_desc, :title, :topic_id, :name, :ext_url, :user_id
  
  belongs_to :topic
  
  validates :image_path, :presence => true
  validates :long_desc, :presence => true
  validates :short_desc, :length => {:minimum => 110, :maximum => 220}, :presence => true
  validates :title, :presence => true
  validates :ext_url, :presence => true
  validates :name, :presence => true, :uniqueness => true, :on => :create
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  skip_before_filter :require_login, :only => [:index]
  
  # GET /blog
  def index
    if(params[:topic])
      if(params[:topic] == "all")
        @blogs = Blog.order(:topic_id)
      else
        @blogs = Blog.where(:topic_id => params[:topic]).order('created_at desc')
      end
    elsif(params[:year] && params[:half])
      if(params[:half] == "1")  
        @blogs = Blog.where(:created_at => ((params[:year]+"-01-01").to_date)..((params[:year]+"-06-30").to_date)).order('created_at desc')
      else
        @blogs = Blog.where(:created_at => ((params[:year]+"-07-01").to_date)..((params[:year]+"-12-31").to_date)).order('created_at desc')
      end
    elsif(params[:name])
      @blogs = Blog.where(:name => params[:name])
    else
      @blogs = Blog.order('created_at desc').limit(5)
    end
    
    @topics = Topic.order(:name)
    
    set_constants
    
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
    @topics = Topic.all
    
    set_constants
    
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
    @topics = Topic.all
  end

  # POST /blogs
  def create
    @blog = Blog.new(params[:blog])
    @blog.user_id = current_user.id
    
    image = params[:blog][:image_path] 
    
    @blog.image_path = image.original_filename
    
    File.open(Rails.root.join('public', 'blog', image.original_filename), 'wb') do |file|
      file.write(image.read)
    end

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url }
      else
        @topics = Topic.all
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /blogs/1
  def update
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to blog_url }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /blogs/1
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blog_url }
    end
  end
  
  private
  
  def set_constants
    @title = t('blog.title') 
    @description = t('blog.description')
    @keywords = t('blog.keywords')
    @blog_active = "active" 
  end
  
end

app/views/blogs/_facebook_send_script.html.erb
<div id="fb-root"></div>
<script>
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/es_ES/all.js#xfbml=1";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>

app/views/blogs/_form.html.erb
<div id="other_form">
  <%= form_for(@blog) do |f| %>
    <% if @blog.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>
        <ul>
          <% @blog.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :topic %><br />
      <%= select("blog", "topic_id", @topics.collect {|t| [ t.name, t.id ] }, {:include_blank => false}) %> <%= link_to 'Admin topics', topics_path %>
    </div>
    <div class="field">
      <%= f.label :name %> <p style="width: 650px">* Este campo es un identificador y ha de ser único y escribirse sin espacios ni caracteres extraños.</p>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :image_path %><br />
      <%= f.file_field :image_path %><br />
    </div>
    <div class="field">
      <%= f.label :ext_url %><br />
      <%= f.text_field :ext_url %>
    </div>
    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :short_desc %><br />
      <%= f.text_field :short_desc %>
    </div>
    <div class="field">
      <%= f.label :long_desc %><br />
      <%= f.text_area :long_desc %>
    </div>
    <div class="field">
      <p style="width: 650px">Algunos ejemplos html:<br />
      Parrafo: &lt;p&gt;texto que sea&lt;/p&gt;<br />
      Parrafo negrita: &lt;p style="font-weight:bold"&gt;texto que sea&lt;/p&gt;<br />
      Parrafo cursiva: &lt;p style="font-style:italic"&gt;texto que sea&lt;/p&gt;<br />
      Parrafo con otro tamaños de letra: &lt;p style="fontsize:20px"&gt;texto que sea&lt;/p&gt;<br />
      Parrafo con un enlace: &lt;p&gt;&lt;a href="http://softlutions.es" target="_blank"&gt;www.softlutions.es&lt/a&gt&lt;/p&gt;<br />
      Parrafo con una imagen: &lt;p&gt;Texto que sea&lt;img src="http://flickr.com/98459" /&gt;Texto que sea&lt;/p&gt;<br /></p>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/blogs/_share.html.erb
<div class="post_comments">
  <!-- Place this tag where you want the share button to render. -->
  <div class="g-plus" data-action="share" data-annotation="bubble" data-href="http://mallorcaror.org/blog?name=<%= name %>"></div>
  <!-- Place this tag after the last share tag. -->
  <script type="text/javascript">
    window.___gcfg = {lang: 'es'};
    (function() {
      var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
      po.src = 'https://apis.google.com/js/plusone.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
    })();
  </script>
  </br></br>
  <a data-url="http://mallorcaror.org/blog?name=<%= name %>" href="https://twitter.com/share" class="twitter-share-button" data-via="MalorcaRoR" data-lang="en" data-related="MallorcaRoR">Tweet</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </br></br>
  <div class="fb-send" data-href="http://mallorcaror.org/blog?name=<%= name %>"></div>
</div>

app/views/blogs/_twitter_plugin.erb
<div class="right_content_wrapper">
  <div class="text_widget">
    <h5><%= t('blog.twitter') %></h5>
    <div class="twitter_message_content">
      <div class="tweet"></div>
    </div>
  </div>
</div>  

app/views/blogs/edit.html.erb
<div id="wrapper">
  <div class="full_width"> 
    <h2>Editing blog</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/blogs/index.html.erb
<div id="wrapper">
  <%= render 'facebook_send_script' %>
  <div class="blog-menu">
    <ul class="sf-menu">
      <li><%= t('blog.topics.title') %>
        <ul>
          <li><%= link_to t('blog.topics.all'), blog_path(:topic => "all") %></li>
          <% @topics.each do |topic| %>
            <li><%= link_to topic.name, blog_path(:topic => topic), :title => topic.description %></li>
          <% end %>
        </ul>
      </li>
      <li><%= t('blog.date.title') %>
        <ul>
          <li><%= link_to t('blog.date.all'), blog_path %></li>
          <li><%= link_to t('blog.date.sec2012'), blog_path(:year => "2012", :half=> "2") %></li>
        </ul>
      </li>
      <% if logged_in? %>
        <li><%= link_to 'Create new Post', new_blog_path %></li>
      <% end %>
    </ul>
  </div>  
  <div class="full_width">
    <% @blogs.each do |blog| %>
      <div class="post">
        <h2><%= blog.title %></h2>
        <div class="post_image">
          <% if blog.image_path.index("blog/")!=nil %>
            <%= link_to(image_tag("/#{blog.image_path}", :alt => blog.title, :title => blog.title, :width => "100"), blog.ext_url, :target => "_blank", :name => blog.name) %>
          <% elsif blog.image_path.index("http")!=nil %>
            <%= link_to(image_tag(blog.image_path, :alt => blog.title, :title => blog.title, :width => "100"), blog.ext_url, :target => "_blank", :name => blog.name) %>
          <% else %>
            <%= link_to(image_tag("/blog/#{blog.image_path}", :alt => blog.title, :title => blog.title, :width => "100"), blog.ext_url, :target => "_blank", :name => blog.name) %>
          <% end %>
        </div>
        <div class="post_details_date_wrapper">
          <div class="post_date" >
            <strong><%= t('blog.post.date') %></strong> <%= blog.created_at.strftime("%d/%m/%Y") %></br>
            Topic: <%= blog.topic.name %></br>
            Posted by: <%= get_user(blog).name %> <%= get_user(blog).surname %> 
          </div>
          <%= render 'share', :name => blog.name %>
          <% if (logged_in? && blog.user_id == current_user.id) %>
            <div class="blog-admin">
              <p><%= link_to 'Edit', edit_blog_path(blog) %></p>
              <p><%= link_to 'Destroy', delete_blog_path(blog), :data => { :confirm=> 'Are you sure?' } %></p>  
            </div>  
          <% end %>
        </div>
        <div class="other_post_details_wrapper">
          <div class="post_content">
            <div class="intro">
            </div>
            <p><%= blog.short_desc %></p>
            </br>
            <%= blog.long_desc.html_safe %>
          </div>
        </div>
        <hr />
      </div>
    <% end %>
  </div>
  <%#= render 'twitter_plugin' %>
</div>

app/views/blogs/new.html.erb
<div id="wrapper">
  <div class="full_width"> 
    <h2>New blog</h2>
    <%= render 'form' %>
  </div>
</div>