config/routes.rb
MallorcaRoR::Application.routes.draw do
  root :to => 'home#index'
  get 'home' => 'home#index', :as => 'home'
  get 'login' => 'users#login_index', :as => 'login'
  post 'login' => 'users#login', :as => 'login'
  get 'logout' => 'users#destroy_session', :as => 'logout'
  
  
  resources :meetups

  resources :users
  
  resources :blogs, :only => [:new, :create, :edit]
  get 'blog' => 'blogs#index', :as => 'blog'
  match 'blog.:id' => 'blogs#update', :via => :put
  match 'delete_blog.:id' => 'blogs#destroy', :as => 'delete_blog'
  
  resources :topics
  
  resources :tasks
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :description, :name
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  # GET /topics
  def index
    @topics = Topic.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /topics/1
  def show
    @topic = Topic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /topics/new
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  def create
    @topic = Topic.new(params[:topic])

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, :notice => 'Topic was successfully created.' }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /topics/1
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to @topic, :notice => 'Topic was successfully updated.' }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /topics/1
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url }
    end
  end
end

app/views/topics/_form.html.erb
<div id="other_form">
  <%= form_for(@topic) do |f| %>
    <% if @topic.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

        <ul>
          <% @topic.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_field :description %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/topics/edit.html.erb
<div id="wrapper">
  <div class="full_width"> 
    <h2>Editing topic</h2>
    <%= render 'form' %>
    <%= link_to 'Show', @topic %> |
    <%= link_to 'Back', topics_path %>
  </div>
</div>

app/views/topics/index.html.erb
<div id="wrapper">
  <div class="full_width"> 
    <h2>Listing topics</h2>

    <table style="width: 100%">
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

      <% @topics.each do |topic| %>
        <tr>
          <td><%= topic.name %></td>
          <td><%= topic.description %></td>
          <td><%= link_to 'Show', topic %></td>
          <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
          <td><%= link_to 'Destroy', topic, :method => :delete, :data => { :confirm=> 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </table>

    <br />

    <%= link_to 'New Topic', new_topic_path %>
  </div>
</div>

app/views/topics/new.html.erb
<div id="wrapper">
  <div class="full_width"> 
    <h2>New topic</h2>
    <%= render 'form' %>
    <%= link_to 'Back', topics_path %>
  </div>
</div>

app/views/topics/show.html.erb
<div id="wrapper">
  <div class="full_width"> 
    <p id="notice"><%= notice %></p>

    <p>
      <b>Name:</b>
      <%= @topic.name %>
    </p>

    <p>
      <b>Description:</b>
      <%= @topic.description %>
    </p>


    <%= link_to 'Edit', edit_topic_path(@topic) %> |
    <%= link_to 'Back', topics_path %>
  </div>
</div>