config/routes.rb
MallorcaRoR::Application.routes.draw do
  root :to => 'home#index'
  get 'home' => 'home#index', :as => 'home'
  get 'login' => 'users#login_index', :as => 'login'
  post 'login' => 'users#login', :as => 'login'
  get 'logout' => 'users#destroy_session', :as => 'logout'
  
  
  resources :meetups

  resources :users
  
  resources :blogs, :only => [:new, :create, :edit]
  get 'blog' => 'blogs#index', :as => 'blog'
  match 'blog.:id' => 'blogs#update', :via => :put
  match 'delete_blog.:id' => 'blogs#destroy', :as => 'delete_blog'
  
  resources :topics
  
  resources :tasks
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="clear"></div>
  <div class="footer">
    <div class="softlutions">
      <%= link_to(image_tag('softlutions.png', :alt => "www.softlutions.es", :title => "www.softlutions.es"), "http://softlutions.es", :target => "_blank") %>
      <p>
        <%= t('footer.softlutions') %><br/>
        <span>
          <%= t('footer.softpriv') %>&nbsp;<%= link_to t('footer.license'), "http://creativecommons.org/licenses/by/3.0/deed.es_ES", :target => "_blank" %>
        </span>
      </p>
    </div>
    <div>
      <%=link_to(image_tag('seal.png', :alt => t('free_culture'), :style => "width:50px;position:absolute;", :title => t('free_culture')), 'https://github.com/abarriga/mallorcaRoR' , :target => '_blank') %>
    </div>
    <div class="data">
      <p>
        <%= "Palma de Mallorca 2012-#{DateTime.now.year}" %><br/>
        <%= link_to t('footer.mail'), "mailto:info@mallorcaror.org" %>
      </p>
    </div>
 </div>
</footer> 

app/views/layouts/_menu.html.erb
<div id="social_bar_wrapper">
  <div id="logo_menu_wrapper">
    <div id="top_menu">
      <ul class="sf-menu">
        <li><%= link_to(image_tag('mallorcaror2.png', :style => "width:78px;margin-top: -17px;"), root_path, :class => @home_active ? @home_active : "") %></li>
        <li><%= link_to t('header.menu.meetup'), meetups_path, :class => @meetup_active ? @meetup_active : "" %></li>
        <li><%= link_to t('header.menu.blog'), blog_path, :class => @blog_active ? @blog_active : "" %></li>
        <% unless (logged_in?) %>
          <li><%= link_to t('header.menu.newuser'), new_user_path, :class => @newuser_active ? @newuser_active : "" %></li>
          <li><%= link_to t('header.menu.login'), login_path, :class => @login_active ? @login_active : "" %></li>
        <% else %>
          <li><%= link_to t('header.menu.task'), tasks_path, :class => @task_active ? @task_active : "" %></li>
          <li><%= link_to current_user.name, current_user, :class => @user_active ? @user_active : "" %></li>
          <li><%= link_to t('header.menu.logout'), logout_path, :data => { :confirm => 'Are you sure?' } %></li>
        <% end %>
      </ul>
    </div>
    <div class="languages">
        <%= link_to 'ES ', :lang => "es" %>|  
        <%= link_to 'EN ', :lang => "en" %>
      </div>
    <div class="clear"></div>
  </div>
</div>

app/views/layouts/_menujs.html.erb
<script type="text/javascript">
  $(document).ready(function(){
    $("#form").val();
  });
</script>

<!-- Menu to Select Setting -->
<script type="text/javascript">
  // DOM ready
  $(document).ready(function(){

    // Create the dropdown base
    $("<select />").appendTo("#top_menu");

    // Create default option "Go to..."
    $("<option />", {
      "selected": "selected",
      "value"   : "",
      "text"    : "Menu Selection..."
    }).appendTo("#top_menu select");

    // Populate dropdown with menu items
    $("#top_menu a").each(function() {
      var el = $(this);
      $("<option />", {
        "value"   : el.attr("href"),
        "text"    : el.text()
      }).appendTo("#top_menu select");
    });

    // To make dropdown actually work
    // To make more unobtrusive: http://css-tricks.com/4064-unobtrusive-page-changer/
    $("#top_menu select").change(function() {
      window.location = $(this).find("option:selected").val();
    });

  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <!--[if IE 7 ]>    <html class= "ie7"> <![endif]-->
  <!--[if IE 8 ]>    <html class= "ie8"> <![endif]-->
  <!--[if IE 9 ]>    <html class= "ie9"> <![endif]-->
  <!--[if lt IE 9]>
  <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
  <![endif]-->
  <head>
    <title><%= @title %></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="<%= @description %>"/>
    <meta name="keywords" content="<%= @keywords %>"/>
    <%= favicon_link_tag %>
    <%= favicon_link_tag "favicon.ico", :type => "image/x-icon"%>
    <%= favicon_link_tag "apple-touch-icon.png", :rel => "apple-touch-icon", :type => "image/png" %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= render '/layouts/menujs' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render '/layouts/menu' %>
    <%= yield %>
    <%= render '/layouts/footer' %>
    <%#= render '/layouts/ganalitics' %>
  </body>
</html>